SELECT own.ITEM_ID, own.ITEM_NAME, own.RARITY
FROM ITEM_INFO AS own
JOIN (
    SELECT ITEM_ID
      FROM ITEM_TREE
      WHERE PARENT_ITEM_ID 
      IN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY='RARE')
) AS joined 
ON own.ITEM_ID = joined.ITEM_ID
ORDER BY ITEM_ID DESC